### ISSUE TITLE
ArcticFox translation

### ISSUE THREAD

**Issue by MoDuLah** [maelstrom2001/ArcticFox#153]
I've completed by 80% the translation of the software in Greek but few controls are not "flexible" based on words/phrase length. So many phrases/words get cut by that.
I've tried to put the shortest words possible still not enough.
![image](https://cloud.githubusercontent.com/assets/7404959/23136840/4f5ae476-f7a7-11e6-9189-3e755581d4bc.png)

**Comment by TBXin** [comment]
If German colleagues were able to put your words, then you can ^^

**Comment by MoDuLah** [comment]
I don't really understand your message. Please enlighten me.
What German have to do with Greek?

**Comment by TBXin** [comment]
I mean that average german words length is higher than Greek and German colleagues done translation very well and all words are still in the limits.

**Comment by MoDuLah** [comment]
English: Preheat (7), Delay (5)
German: vorheizen (9), Pause (5),
Greek: Προθέρμανση (11), Αναμονή(7)
Ehm. Also that average thing doesn't seems correct. Greek have a Guinness Record about longest word. 172 characters ;)

**Comment by MoDuLah** [comment]
It's easier to set a button parameter to Autosize = true
Than chopping of Greek words.

**Comment by westor7** [comment]
Because i have translate a lot of programs into the Greek language , believe that the Greek language translation characters require more space because in some words that are simple to translated into the German or into an other language into the Greek to be a valid translation into a simple word or phrase it need a lot of more characters, so really you need to do something with that because the @MoDuLah here has right, that's one reason that the most of programs are not translated into the Greek language because the spacing issue part that needs re-arrange.

**Comment by Dil3mm4** [comment]
I could translate it into Italian, if needed.

**Comment by MoDuLah** [comment]
This is the file Westor7 if you have any idea to improve it go ahead.
[EL.lpack.txt](https://github.com/maelstrom2001/ArcticFox/files/790780/EL.lpack.txt)

**Comment by Schwinni77** [comment]
Invalid because the NFirmwareEditor repository is the right place for translations: https://github.com/TBXin/NFirmwareEditor

**Comment by MoDuLah** [comment]
thanks @Schwinni77 i wish @TBXin was guiding me there in the first place.
