### ISSUE TITLE
little help please?

### ISSUE THREAD

**Issue by hahalol12343** [maelstrom2001/ArcticFox#228]
hello i like this firmware so much but i have one question why does it only show one battery icon not the 4 of them i have rx300

**Comment by maelstrom2001** [comment]
The main view is unified for all boxes, there is single battery icon displaying total charge level. Why? Because multiple icons are useless, it's a waste of display area. Individual voltages can be monitored via infoline or info screen. If your batteries are imbalanced, box will show it. All the rest of the time you do not have to worry about disbalance, charge level of every cell etc.
