### ISSUE TITLE
Can't work out how to get + and - buttons back to the correct orientation on dual after flipping the screen.

### ISSUE THREAD

**Issue by wackydude1234** [maelstrom2001/ArcticFox#229]
I flipped the screen on the pico dual by holding + & - when powered off, but now the - button increases wattage and the + decreases wattage, but i want the screen in this orientation, can i put the buttons back without having the screen flipped the other way? Build: 170201

**Comment by wackydude1234** [comment]
also the mod will only go to 100w.

**Comment by maelstrom2001** [comment]
Flipping screen by holding + and - buttons also swaps these buttons, this is by design. If you prefer to do not swap them, switch option in NToolbox:
![](http://i.imgur.com/fCsoHlz.png)

To avoid 25 amps limit of output current use [ the latest nightlies](https://github.com/maelstrom2001/ArcticFox/wiki/Changelog) (firmware and NToolbox)

**Comment by wackydude1234** [comment]
Ah thank you, also what nightly do i use? I tried to do the top one and it said it's not compatible

**Comment by maelstrom2001** [comment]
> it said it's not compatible

For nightly builds you should use [nightly NToolbox](https://ci.appveyor.com/project/TBXin/NFirmwareEditor/branch/master/artifacts)

**Comment by wackydude1234** [comment]
Thank you, your time and reply is appreciated.

**Comment by wackydude1234** [comment]
This is now solved thanks!
