### ISSUE TITLE
Quick question, not sure where to ask

### ISSUE THREAD

**Issue by sethiano** [maelstrom2001/ArcticFox#261]
Sorry if I am posting this in the wrong section. I just got all this installed and working, and it's totally awesome.

I was just curious if this firmware fixes performance things like Wismec mismatched battery drain and stuff like that, or is it only new features?

Thanks in advance.

Seth

**Comment by TBXin** [comment]
> I was just curious if this firmware fixes performance things like Wismec mismatched battery drain and stuff like that, or is it only new features?

All at once :) Some things like incorrect battery readings can't be fixed programmatically because this is hardware issue, but our firmware is provides such mechanism as BVO (Battery Voltage Offset), which can help users to fix incorrect readings by adding to or subtracting user-defines values (in volts) from actual devices readings.

Some things are same if we are comparing with a OFW, like minimal resistance, maximum current output, etc.
Some things are better, some things are different.
