### ISSUE TITLE
profile page

### ISSUE THREAD

**Issue by sigaraci** [maelstrom2001/ArcticFox#280]
Sometimes when I wake up the device, the profile selection page comes up. what is the reason of this?

**Comment by maelstrom2001** [comment]
It happens because of enabled Smart mode. If detected atomizer resistance is not matched to any saved, you'll have be prompted to assign profile like for new coil. You can set a little higher range in Smart settings or disable Smart if you don't use it.
In upcoming release Smart mode will be improved and will have new option to prevent re-detection on wakeup. This will eliminate erratic switching/assignments etc.

**Comment by sigaraci** [comment]
thank you. i wait this

**Comment by maelstrom2001** [comment]
Released.
