### ISSUE TITLE
Menu opening time

### ISSUE THREAD

**Issue by sigaraci** [maelstrom2001/ArcticFox#292]
Thank you for your efforts. We need to press the fire and + keys for 1 second to open the menu. If you can do this in 1/5 second, it will be very functional. Thank you

**Comment by TBXin** [comment]
All people are impossible to please. 
Some people like opening in 1 second, someone for 1/5 of a second. 
The setting for this is not meaningful, since during normal usage of the device, you will not often enter the menu.

Lifehack: for example you can assign "Main Menu" command to the "2 clicks" and device will open menu immediately after clicks.

**Comment by adzam016** [comment]
What an odd request :-1:
