### ISSUE TITLE
not a issues/ just a thanks for your work 

### ISSUE THREAD

**Issue by docdeath** [maelstrom2001/ArcticFox#343]
big thanks to team here for wicked firmware and updates for rx300 /and other mods to

**Comment by acevalsl** [comment]
Same.....txs

**Comment by kyan31** [comment]
Yep, thanks to all of the Arctic fox team for developing such a wonderful firmware. I just found out about this today and I'm loving it, literally made my RX2/3 a whole new device. It's just like having a DNA board, I'm actually lost for words because I didn't think the standard chips were capable of all these features. Thank you again!

**Comment by snigel** [comment]
Great stuff!

**Comment by acevalsl** [comment]
Where can i make a donation for your job??

**Comment by TBXin** [comment]
> Where can i make a donation for your job??

Here https://nfeteam.org you can find donate button on the top panel.

**Comment by acevalsl** [comment]
donation PayPal made
txs

**Comment by TBXin** [comment]
> donation PayPal made

Thanks! We really appreciate it.

**Comment by derTim** [comment]
Also big thanks from me! Really missed AF on the new Primo 2.0 :)

**Comment by amrdia** [comment]
u guys are awesome

**Comment by Sonicaki** [comment]
I would like to say a big THANK YOU too!!!
Foxy skin rocks!! perfect design!
Thank you guys for everything!

**Comment by Hunterror77** [comment]
Thank you all , keep up this excellent work!
