### ISSUE TITLE
Energy consumption stat

### ISSUE THREAD

**Issue by lentis720** [maelstrom2001/ArcticFox#375]
I just thought of this. Would it be possible to add another counter (like puff and time counters) for Wh (watt-hours) used? Right now it would only be possible to know this value if you're using VariWatt mode with a single value throughout (multiply watts by time used). But if you're changing the wattage often or if you're using TC / power curves / preheat it's impossible to calculate.

It could be useful for battery troubleshooting if doable. The energy calculated wouldn't take the inefficiency (chipset heat) into account but it would still show how the batteries are aging.

Again, I don't know if this is possible. I'm just throwing this idea to you guys.

**Comment by TBXin** [comment]
Hello,

Thanks for your suggestion, but we can't keep extended statistics on the device since there are no special place and ROM size is limited.

Also, we can't calculate how much Wh was taken from batteries because PCB can't measure it.
Theoretically we can calculate only how much Joules were given to atty and again, we don't have space in the ROM to store this kind of the information.
