### ISSUE TITLE
Screen Stealth mode in Power Bank Mode  support request

### ISSUE THREAD

**Issue by ilyxa** [maelstrom2001/ArcticFox#383]
While running box (Cuboid 200, Pico 75W) in Power Bank mode, screen is on all time which is not good for OLED display. Can you please add support for stealth mode in Power Bank mode?

**Comment by ZenFree** [comment]
Personally, I would prefer settings for screen timeout instead.

**Comment by ilyxa** [comment]
Not important, just turn screen off in any manner ;)

**Comment by maelstrom2001** [comment]
There is no problem to turn off display completely, but I personally prefer to see in which state box is right now. If it works (Power Bank output is on), it should indicate it in any way. Now used 0% brightness level instead of user defined, I think it should not lead to OLED degradation dramatically. Eventually, it is a matter of taste and a point of view. We do not reject categorically, but we'll not promise anything either. Thanks for understanding.

**Comment by maelstrom2001** [comment]
https://nfeteam.org/forum/threads/arcticfox-170517.30/
