### ISSUE TITLE
RTC Speed?

### ISSUE THREAD

**Issue by FaberfoX** [maelstrom2001/ArcticFox#66]
Couldn't find anything about this value, I'm assuming it's for compensating for RTC drift without LSL. Any info on how to calculate the proper value? Could it be possible for NFEToolbox to auto adjust it measuring difference betweeen real and expected value?

Thanks!

**Comment by maelstrom2001** [comment]
Some boxes (VTC-Mini, Cuboid/Mini, Presa 75W, RX75, RX200S, RX2/3) does not have the needed 32kHz crystal soldered on the pcb to regulate the clock speed; so, another time source is used to drive the clock. Since its frequency is quite different, a clock speed ratio is needed to regulate the clock. As long as the box is awake (you're using it), the clock is regulated by the external 12.000MHz crystal, which is an accurate time source. Problem arises when the box enters sleep mode, since the crystal is switched off and the only clock source is the somewhat unreliable 10kHz internal oscillator of the processor. Clock drift mostly occurs when the box is switched off or sleeping.

The procedure to adjust the clock speed ratio is as follow:

- First, setup time accurately via the date/time menu or sync it with NToolbox.
- Let the box enter sleep mode (leave it alone or switch it off) for several hours. I suggest you're doing this before sleeping yourself.
- Awake the box and go into the "Clk Speed" menu; do not let the box enter sleep mode again in between, or you'll have to redo the whole thing.
- Using + and - buttons, adjust the time shown on top of the screen to catch up the real time. The number shown in the center of the screen is the clock speed ratio; reasonable values should be around 32~34000.
- Once you have adjusted the time to the real time, click fire to save the new clock speed ratio. Your clock should now be as accurate as it can. If not, try to repeat the procedure. Accuracy of a few seconds per day can be achieved this way.

(c) ClockSelect

LSL will give you more precise time counting, so can assume this function obsolete.
